Package items
kartoza/ckanext-dalrrd-emc-dcpr pull request #143
Opened 2022-03-10 14:35 UTC by Fanevanjanahary

fixes #114 #127

- [x] Add pagination
- [x] Add the link detail on item title

2022-03-10 15:36 UTC, ricardogsilva requested changes
Seems to work OK. However, the link to the item detail page is perhaps too subtle. Please make the hyperlink more pronounced.

My suggestion is to make hyperlinks use the green color that is used elsewhere to denote buttons and links, such as in the search filters:

![image](https://user-images.githubusercontent.com/732010/157696702-c36ea4dc-ff35-4e81-a31a-d0756983b6b5.png)

Don't make them bold though

2022-03-10 16:15 UTC, Fanevanjanahary commented
hi @ricardogsilva please is that ok or does the font-weight need to be lower?

![image](https://user-images.githubusercontent.com/12623986/157706582-de8f94cf-43ba-4822-b4bf-1c4df75f5cec.png)

2022-03-10 17:03 UTC, ricardogsilva requested changes
Almost good, I'd just ask that you revert the backend change, which is unrelated to this issue

2022-03-10 17:03 UTC, ricardogsilva commented on ckanext/dalrrd_emc_dcpr/logic/action/dcpr.py
> +        model.repo.commit()
This change seems totally unrelated to this PR. I guess you took it from one of the pending PRs. Please revert this, as I don't want to mix backend and frontend changes in this issue

2022-03-11 09:56 UTC, ricardogsilva approved these changes
Nice, thanks!

2022-03-11 09:56 UTC, merged